apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-app
  namespace: kafka
spec:
  replicas: 2
  selector:
    matchLabels:
      app: producer-app
  template:
    metadata:
      labels:
        app: producer-app
    spec:
      containers:
        - name: producer-app
          image: diwelle/producer-app:producer-app
          

